//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	/// <summary>
	/// DomainModel DRMRRBRRMProyectoIPSDomainModel
	/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("a6d8d001-644d-4c71-a77d-e146e9fd4be5")]
	public partial class DRMRRBRRMProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DRMRRBRRMProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xa6d8d001, 0x644d, 0x4c71, 0xa7, 0x7d, 0xe1, 0x46, 0xe9, 0xfd, 0x4b, 0xe5);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DRMRRBRRMProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(FONDO),
				typeof(Clase),
				typeof(Atributo),
				typeof(Operacion),
				typeof(Parametro),
				typeof(FONDOHasClase),
				typeof(ClaseHasAtributo),
				typeof(RelacionBase),
				typeof(ClaseHasOperacion),
				typeof(RelacionHerencia),
				typeof(RelacionAgregacion),
				typeof(RelacionAsociacion),
				typeof(OperacionHasParametro),
				typeof(DRMRRBRRMProyectoIPSDiagram),
				typeof(ConectorBaseDisplay),
				typeof(ConectorHerenciaDisplay),
				typeof(ClaseDisplay),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.ConnectorRolePlayerChanged),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemAddRule),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemDeleteRule),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemRolePlayerChangeRule),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Clase), "Nombre", Clase.NombreDomainPropertyId, typeof(Clase.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "NombreAtributo", Atributo.NombreAtributoDomainPropertyId, typeof(Atributo.NombreAtributoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TIpo", Atributo.TIpoDomainPropertyId, typeof(Atributo.TIpoPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "NombreOperacion", Operacion.NombreOperacionDomainPropertyId, typeof(Operacion.NombreOperacionPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "Tipo", Operacion.TipoDomainPropertyId, typeof(Operacion.TipoPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "Nombre", Parametro.NombreDomainPropertyId, typeof(Parametro.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "Tipo", Parametro.TipoDomainPropertyId, typeof(Parametro.TipoPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionBase), "CardOrigen", RelacionBase.CardOrigenDomainPropertyId, typeof(RelacionBase.CardOrigenPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionBase), "CardDestino", RelacionBase.CardDestinoDomainPropertyId, typeof(RelacionBase.CardDestinoPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionBase), "NombreRel", RelacionBase.NombreRelDomainPropertyId, typeof(RelacionBase.NombreRelPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionHerencia), "DisjuntaSolapada", RelacionHerencia.DisjuntaSolapadaDomainPropertyId, typeof(RelacionHerencia.DisjuntaSolapadaPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionHerencia), "TotalParcial", RelacionHerencia.TotalParcialDomainPropertyId, typeof(RelacionHerencia.TotalParcialPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionAgregacion), "TipoAgregacion", RelacionAgregacion.TipoAgregacionDomainPropertyId, typeof(RelacionAgregacion.TipoAgregacionPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(FONDOHasClase), "FONDO", FONDOHasClase.FONDODomainRoleId),
				new DomainRolePlayerInfo(typeof(FONDOHasClase), "Clase", FONDOHasClase.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionBase), "SourceClase", RelacionBase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionBase), "TargetClase", RelacionBase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Clase", ClaseHasOperacion.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Operacion", ClaseHasOperacion.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHerencia), "Hijo", RelacionHerencia.HijoDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHerencia), "TargetClase", RelacionHerencia.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionAgregacion), "SourceClase", RelacionAgregacion.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionAgregacion), "TargetClase", RelacionAgregacion.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionAsociacion), "SourceClase", RelacionAsociacion.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionAsociacion), "TargetClase", RelacionAsociacion.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametro), "Operacion", OperacionHasParametro.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametro), "Parametro", OperacionHasParametro.ParametroDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementMap.Add(typeof(FONDO), 0);
				createElementMap.Add(typeof(Clase), 1);
				createElementMap.Add(typeof(Atributo), 2);
				createElementMap.Add(typeof(Operacion), 3);
				createElementMap.Add(typeof(Parametro), 4);
				createElementMap.Add(typeof(DRMRRBRRMProyectoIPSDiagram), 5);
				createElementMap.Add(typeof(ConectorBaseDisplay), 6);
				createElementMap.Add(typeof(ConectorHerenciaDisplay), 7);
				createElementMap.Add(typeof(ClaseDisplay), 8);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new FONDO(partition, propertyAssignments);
				case 1: return new Clase(partition, propertyAssignments);
				case 2: return new Atributo(partition, propertyAssignments);
				case 3: return new Operacion(partition, propertyAssignments);
				case 4: return new Parametro(partition, propertyAssignments);
				case 5: return new DRMRRBRRMProyectoIPSDiagram(partition, propertyAssignments);
				case 6: return new ConectorBaseDisplay(partition, propertyAssignments);
				case 7: return new ConectorHerenciaDisplay(partition, propertyAssignments);
				case 8: return new ClaseDisplay(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementLinkMap.Add(typeof(FONDOHasClase), 0);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 1);
				createElementLinkMap.Add(typeof(RelacionBase), 2);
				createElementLinkMap.Add(typeof(ClaseHasOperacion), 3);
				createElementLinkMap.Add(typeof(RelacionHerencia), 4);
				createElementLinkMap.Add(typeof(RelacionAgregacion), 5);
				createElementLinkMap.Add(typeof(RelacionAsociacion), 6);
				createElementLinkMap.Add(typeof(OperacionHasParametro), 7);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new FONDOHasClase(partition, roleAssignments, propertyAssignments);
				case 1: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 2: return new RelacionBase(partition, roleAssignments, propertyAssignments);
				case 3: return new ClaseHasOperacion(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionHerencia(partition, roleAssignments, propertyAssignments);
				case 5: return new RelacionAgregacion(partition, roleAssignments, propertyAssignments);
				case 6: return new RelacionAsociacion(partition, roleAssignments, propertyAssignments);
				case 7: return new OperacionHasParametro(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DRMRRBRRMProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DRMRRBRRMProyectoIPSDomainModel.resourceManager == null)
				{
					DRMRRBRRMProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DRMRRBRRMProyectoIPSDomainModel).Assembly);
				}
				return DRMRRBRRMProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DRMRRBRRMProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DRMRRBRRMProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DRMRRBRRMProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DRMRRBRRMProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DRMRRBRRMProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return DRMRRBRRMProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DRMRRBRRMProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DRMRRBRRMProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DRMRRBRRMProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return DRMRRBRRMProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRMRRBRRMProyectoIPSDeleteClosure : DRMRRBRRMProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DRMRRBRRMProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRMRRBRRMProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DRMRRBRRMProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.DRMRRBRRMProyectoIPS.FONDOHasClase.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRMRRBRRMProyectoIPS.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRMRRBRRMProyectoIPS.ClaseHasOperacion.OperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DRMRRBRRMProyectoIPS.OperacionHasParametro.ParametroDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRMRRBRRMProyectoIPSCopyClosure : DRMRRBRRMProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DRMRRBRRMProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DRMRRBRRMProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DRMRRBRRMProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoAgregacion
	/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoAgregacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoAgregacion
	{
		/// <summary>
		/// Inclusiva
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoAgregacion.Inclusiva
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoAgregacion/Inclusiva.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Inclusiva,
		/// <summary>
		/// Referencial
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoAgregacion.Referencial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoAgregacion/Referencial.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Referencial,
	}
}
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Cardinalidades
	/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Cardinalidades
	{
		/// <summary>
		/// Ol
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades.Ol
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades/Ol.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Ol,
		/// <summary>
		/// ON
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades.ON
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades/ON.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		ON,
		/// <summary>
		/// l
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades.l
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades/l.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		l,
		/// <summary>
		/// IN
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades.IN
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades/IN.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		IN,
		/// <summary>
		/// O
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades.O
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades/O.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		O,
		/// <summary>
		/// NM
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades.NM
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.Cardinalidades/NM.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		NM,
	}
}
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: DisjuntaSolapada
	/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.DisjuntaSolapada
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum DisjuntaSolapada
	{
		/// <summary>
		/// Disjunta
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.DisjuntaSolapada.Disjunta
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.DisjuntaSolapada/Disjunta.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Disjunta,
		/// <summary>
		/// Solapada
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.DisjuntaSolapada.Solapada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.DisjuntaSolapada/Solapada.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Solapada,
	}
}
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TotalParcial
	/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TotalParcial
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TotalParcial
	{
		/// <summary>
		/// Total
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TotalParcial.Total
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TotalParcial/Total.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Total,
		/// <summary>
		/// Parcial
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TotalParcial.Parcial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TotalParcial/Parcial.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Parcial,
	}
}
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoDeDato
	/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDeDato
	{
		/// <summary>
		/// Int
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/Int.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Int,
		/// <summary>
		/// Long
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.Long
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/Long.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Long,
		/// <summary>
		/// Float
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.Float
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/Float.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Float,
		/// <summary>
		/// Double
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.Double
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/Double.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Double,
		/// <summary>
		/// Char
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.Char
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/Char.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Char,
		/// <summary>
		/// String
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/String.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		String,
		/// <summary>
		/// Bool
		/// Description for UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato.Bool
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DRMRRBRRMProyectoIPS.TipoDeDato/Bool.Description", typeof(global::UPM_IPS.DRMRRBRRMProyectoIPS.DRMRRBRRMProyectoIPSDomainModel), "UPM_IPS.DRMRRBRRMProyectoIPS.GeneratedCode.DomainModelResx")]
		Bool,
	}
}

