//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DRMRRBRRM_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DRMRRBRRMProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DRMRRBRRMProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DRMRRBRRMProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DRMRRBRRMProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DRMRRBRRMProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDRMRRBRRMProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DRMRRBRRMProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string DRMRRBRRMProyectoIPSPackageId = "2608c69d-9eaf-4ee3-97ac-78a988eba9ac";
		
		// Editor factory identifier
		public const string DRMRRBRRMProyectoIPSEditorFactoryId = "7e075449-42e6-4b75-89d1-a864671a3556";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DRMRRBRRMProyectoIPSModelExplorerToolWindowId = "17718c13-3e12-4ec6-a8c7-4d194dfd245d";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DRMRRBRRMProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DRMRRBRRMProyectoIPSCommandSetId = "504113e7-b3ba-4fac-824c-73a9be7415f5";
	}
}